services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: kronset
      POSTGRES_PASSWORD: kronset
      POSTGRES_DB: kronset
    ports:
      - "5432:5432"
    volumes:
      - kronset_pg:/var/lib/postgresql/data

  api:
    build:
      context: ../apps/api

    environment:
      DATABASE_URL: postgresql://kronset:kronset@db:5432/kronset

      # EXEMPLO: datasource (pode ser o mesmo Postgres ou outro)
      KRONSET_CONN_PG_DEMO: postgresql://kronset:kronset@db:5432/kronset
    
    ports:
      - "8000:8000"
    depends_on:
      - db

  web:
    build:
      context: ../apps/web
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  kronset_pg:
